{"name": "Успешная проверка изменения имени существующего пользователя", "status": "failed", "statusDetails": {"message": "AssertionError: assert (401 == 200)\n +  where 401 = <Response [401]>.status_code", "trace": "self = <test_user.TestUserDataChanging object at 0x000001499F9BA600>, user = {'access_token': None, 'email': '565@ya.ru', 'name': 'kyyvfip', 'password': 8309983}, name = 'new_name'\n\n    @allure.title('Успешная проверка изменения имени существующего пользователя')\n    @pytest.mark.parametrize('name', ['new_name'])\n    def test_user_changed_name_successful_result(self, user, name):\n        payload = {'name': name}\n        headers = {'Authorization': user['access_token']}\n        response = requests.patch(data.user_info, data=payload, headers=headers)\n>       assert response.status_code == 200 and response.json().get(\"success\") is True and response.json()['user']['name'] == name\nE       assert (401 == 200)\nE        +  where 401 = <Response [401]>.status_code\n\ntests.py\\test_user.py:60: AssertionError"}, "parameters": [{"name": "name", "value": "'new_name'"}], "start": 1717592833382, "stop": 1717592833760, "uuid": "201e4781-8041-4c2b-b1c9-93016b8811dd", "historyId": "abc0c414a0ad19e4ec46d6d44e046220", "testCaseId": "7340a3758555fd416944d7d514143a28", "fullName": "tests.py.test_user.TestUserDataChanging#test_user_changed_name_successful_result", "labels": [{"name": "parentSuite", "value": "tests.py"}, {"name": "suite", "value": "test_user"}, {"name": "subSuite", "value": "TestUserDataChanging"}, {"name": "host", "value": "DESKTOP-AQPR8BL"}, {"name": "thread", "value": "6544-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.py.test_user"}]}