{"name": "Проверка создания заказа с некорректно заданным ингредиентом", "status": "passed", "start": 1717593099812, "stop": 1717593100087, "uuid": "c5a5e3f9-93e1-4d72-93d2-a71ca63b5bec", "historyId": "ad2923b87d22f3c464091cc531a838d9", "testCaseId": "ad2923b87d22f3c464091cc531a838d9", "fullName": "tests.py.test_order.TestOrderCreating#test_orders_wrong_ingredient_failed", "labels": [{"name": "parentSuite", "value": "tests.py"}, {"name": "suite", "value": "test_order"}, {"name": "subSuite", "value": "TestOrderCreating"}, {"name": "host", "value": "DESKTOP-AQPR8BL"}, {"name": "thread", "value": "18104-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.py.test_order"}]}