{"name": "Проверка создания заказа с некорректно заданным ингредиентом", "status": "passed", "start": 1717592825282, "stop": 1717592825540, "uuid": "7e99e71c-e4a4-4209-93dd-433937847d2a", "historyId": "ad2923b87d22f3c464091cc531a838d9", "testCaseId": "ad2923b87d22f3c464091cc531a838d9", "fullName": "tests.py.test_order.TestOrderCreating#test_orders_wrong_ingredient_failed", "labels": [{"name": "parentSuite", "value": "tests.py"}, {"name": "suite", "value": "test_order"}, {"name": "subSuite", "value": "TestOrderCreating"}, {"name": "host", "value": "DESKTOP-AQPR8BL"}, {"name": "thread", "value": "6544-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.py.test_order"}]}